apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: magento
  name: magento
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 80
  selector:
    io.kompose.service: magento
status:
  loadBalancer: {}
