apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      database: db
  # serviceName: db    
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        database: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: magento-secret
                  key: mysql-database
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: magento-secret
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: magento-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: magento-secret
                  key: mysql-user
          image: mysql:5.7
          # args:
          #   - "--ignore-db-dir=lost+found"
          name: db
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      restartPolicy: Always
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-claim-1
#status: {}
