apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 27Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

